/**
 * @brief   The OutdoorLightSwitch module enables or disables a group of light switches 
 *          at times of the day configured by the user. 
 * 
 * @details It does this by signing up for event signals generated by zwave devices on 
 *          the network or system events. How?
 * 
 * @details The general design for all app modules is as follows:
 * 
 * @details All app modules implement networkNotification(networkDevicesJSON) called by 
 *          the application at startup and every time the network device list changes. 
 *          The app passes a JSON object detailing every device on the network and every 
 *          system service available so that this function may inspect the network. 
 *          This function returns a filtered JSON object with the devices and service it 
 *          wants to receive events from.
 *          
 * @details This module only has knowledge of the devices it can control and the devices
 *          and system services that it wants to receive events from. The application
 *          knows nothing of the device functions except how to route events.
 * 
 * @details The JSON Format for network devices is as follows:
 * 
 * @details {
 *              "nodeId" : <integer>,
 *              "name" : "<user assigned name>",
 *              "description" : "<user assigned description>",
 *              "deviceType" : "<?>"
 *          }
 */

//import { Driver } from "zwave-js"



const networkNotification = (driver) => {

    driver.controller.nodes.forEach(node => {
        switch(node.) {
            case "":
                break;
            case "":
                break;
            default:

        }
    }); 
        
}



export default networkNotification

